package com.cordys.coe.ac.fileconnector;

import com.eibus.localization.message.Message;
import com.eibus.localization.message.MessageSet;

/**
 * This code is generated by running com.cordys.coe.cep.wizards.localization.CoEMessageGenerator.
 */
public class LogMessages
{
    /**
     * Holds the definition of the message set.
     */
    public static final MessageSet MESSAGE_SET = MessageSet.getMessageSet("com.cordys.coe.ac.fileconnector.LogMessages");

    /**
     * Holds the definition of the message with ID DriveMappingUnreadable. Message text: Exception
     * reading drive mappings
     */
    public static final Message DRIVE_MAPPING_UNREADABLE = MESSAGE_SET.getMessage("DriveMappingUnreadable");
    /**
     * Holds the definition of the message with ID NoConnectorFound. Message text: No connector
     * object found. Aborting.
     */
    public static final Message NO_CONNECTOR_FOUND = MESSAGE_SET.getMessage("NoConnectorFound");
    /**
     * Holds the definition of the message with ID NoConfigurationFound. Message text: No
     * application configuration found. Aborting.
     */
    public static final Message NO_CONFIGURATION_FOUND = MESSAGE_SET.getMessage("NoConfigurationFound");
    /**
     * Holds the definition of the message with ID CoeLibVersionInvalid. Message text: There is a
     * problem with the CoE library version.
     */
    public static final Message COE_LIB_VERSION_INVALID = MESSAGE_SET.getMessage("CoeLibVersionInvalid");
    /**
     * Holds the definition of the message with ID UnableToOpenConnector. Message text: Unable to
     * open the connector object.
     */
    public static final Message UNABLE_TO_OPEN_CONNECTOR = MESSAGE_SET.getMessage("UnableToOpenConnector");
    /**
     * Holds the definition of the message with ID UnableToLoadCharset. Message text: Unable to load
     * the custom character set provider.
     */
    public static final Message UNABLE_TO_LOAD_CHARSET = MESSAGE_SET.getMessage("UnableToLoadCharset");
    /**
     * Holds the definition of the message with ID UnableToGetConfigurationElement. Message text:
     * Unable to get the configuration element.
     */
    public static final Message UNABLE_TO_GET_CONFIGURATION_ELEMENT = MESSAGE_SET.getMessage("UnableToGetConfigurationElement");
    /**
     * Holds the definition of the message with ID UnableToCreateMapping. Message text: The mapping
     * to {0} could not be created
     */
    public static final Message UNABLE_TO_CREATE_MAPPING = MESSAGE_SET.getMessage("UnableToCreateMapping");
    /**
     * Holds the definition of the message with ID TransactionFailed. Message text: FileConnector
     * transaction failed.
     */
    public static final Message TRANSACTION_FAILED = MESSAGE_SET.getMessage("TransactionFailed");
    /**
     * Holds the definition of the message with ID CONNECTOR_MANAGEMENT_DESCRIPTION. Message text:
     * File Connector
     */
    public static final Message CONNECTOR_MANAGEMENT_DESCRIPTION = MESSAGE_SET.getMessage("CONNECTOR_MANAGEMENT_DESCRIPTION");
}
